---

- hosts: all
  become: true
  pre_tasks:

    - name: Ubuntu Update
      tags: always
      apt:
        upgrade: dist
        update_cache: yes


- hosts: all
  become: true
  tasks:

    - name: Install Glance
      apt:
        name:
          - glance
        state: latest

    - name: Install Keystone
      apt:
        name:
          - keystone
        state: latest

    - name: Instal nova
      apt:
        name:
          - nova-compute
        state: latest
